[workspace]
members = ["backend", "desktop"]
default-members = ["backend"]
resolver = "2"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1

[profile.fire]
inherits = "release"
debug = true
strip = true
opt-level = 3
lto = true
codegen-units = 1

