[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lints.clippy]
enum_glob_use = 'deny'
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -2 }

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
